### ISSUE TITLE
error when syncing (Anki 2.1.22)

### ISSUE THREAD

**Issue by MetalFir** [ig3/anki-limitnew#4]
Thanks for the add-on it's a lifesaver. Unfortunately I keep getting the error below when syncing causing it to disable the add-on

Syncing failed:
Traceback (most recent call last):
  File "aqt/sync.py", line 429, in _sync
  File "aqt/sync.py", line 409, in _abortingSync
  File "anki/sync.py", line 137, in sync
  File "anki/sync.py", line 219, in sanityCheck
  File "anki/schedv2.py", line 69, in reset
  File "anki/schedv2.py", line 378, in _resetNew
  File "anki/schedv2.py", line 375, in _resetNewCount
  File "anki/schedv2.py", line 209, in _walkingCount
  File "anki/schedv2.py", line 477, in _deckNewLimitSingle
  File "anki/hooks.py", line 407, in __call__
  File "/Users/xxxxxx/Library/Application Support/Anki2/addons21/anki-limitnew-master/versions/new_hook.py", line 343, in schedulerNewLimitForSingleDeck
    newLimit = myDeckNewLimitSingle(mw.col.sched, deck)
AttributeError: 'NoneType' object has no attribute 'sched

**Comment by ig3** [comment]
Thanks for letting me know. I don't have anything to sync to, so not sure how I can test a fix but I'll have a look and see what I can do.

**Comment by ig3** [comment]
It seems wrong that mw.col would be NoneType but evidently that is what happened. I am suspicious that you have some other problem causing this, and you should probably find and resolve that, but I don't know the sync code: maybe it does work without a collection on the main window.

In any case, I have committed a change to detect mw.col being NoneType and avoid accessing mw.col.sched if it is. This shouldn't cause any problem for normal operation, when mw.col is not NoneType. Maybe you could try this update (you will have to install it from this repository - I haven't updated ankiweb). If it works, I'll update ankiweb.

**Comment by TingTingin** [comment]
i had the same problem on anki 2.1.22 and after swapping the newhook.py file it fixed it thx

**Comment by ig3** [comment]
Long overdue but I'll put a new release onto ankiweb today. Totally new implementation for Anki > 2.1.26.
